FROM node:22.3.0

WORKDIR /app
COPY ../ .
RUN corepack enable
RUN yarn install --immutable

WORKDIR /app/Tonomy-Communication
RUN yarn install --immutable
RUN yarn link ../
RUN yarn run build

EXPOSE 5000

CMD [ "yarn", "run", "start:prod" ]